version: "3.8"

services:
  server1:
    container_name: server1
    build: ./server
    ports:
      - "3001:3000"
    networks:
      - proxy_network

  server2:
    container_name: server2
    build: ./server
    ports:
      - "3002:3000"
    networks:
      - proxy_network

  server3:
    container_name: server3
    build: ./server
    ports:
      - "3003:3000"
    networks:
      - proxy_network

  nginx:
    container_name: proxy_server
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      - proxy_network
    depends_on:
      - server1
      - server2
      - server3

networks:
  proxy_network:
    driver: bridge